services:
  postgres:
    image: postgres:17.7-alpine
    environment:
      POSTGRES_DB: loans
      POSTGRES_USER: loans
      POSTGRES_PASSWORD: loans
    ports:
      - "5452:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U loans -d loans"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pg-loans:/var/lib/postgresql/data
volumes:
  pg-loans: